server:
  port: 8080



spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${ia.db.host}:3306/hm-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  cloud:
    nacos:
      server-addr: 192.168.10.128:8848
  data:
    redis:
      port: 6379
      host: redis-service
      client-name: user-service  # 服务名-环境-实例ID,使用CLIENT LIST可查看所有连接和对应的客户端名称
geetest:
  captcha-id: "你的captcha_id"
  key: "你的key"

aliyun:
  sms:
    access-key-id: LTAI5tXXXXXXXXXXXX
    access-key-secret: xxxxxxxxxxxxxxxxxxxxxx
    sign-name: 冰美式商城
    template-code: SMS_123456789


#jwt:
#  # 默认使用 hs256
#  algorithm: hs256
#  secret: "your-256-bit-secret-key-for-hs256-must-be-at-least-32-chars"
#  expiration: 3600

# 如需切换至 rs256，配置如下：
# jwt:
#   algorithm: rs256
#   privateKey: classpath:private_key.pem   # 或直接放 PEM 内容
#   publicKey: classpath:public_key.pem
#   expiration: 3600


