registry {
  type = "nacos"
  nacos {
    application = "seata-server"
    serverAddr = "nacos:8848"
    group = "SEATA_GROUP"
    namespace = ""
    username = "nacos"
    password = "nacoss"
    # Nacos 2.4 auth 需要 identity 字段
    accessKey = "serverIdentity"
    secretKey = "security"
  }
}

config {
  type = "nacos"
  nacos {
    serverAddr = "nacos:8848"
    group = "SEATA_GROUP"
    namespace = ""
    username = "nacos"
    password = "nacoss"
    accessKey = "serverIdentity"
    secretKey = "security"
    dataId = "seataServer.properties"
  }
}
