server:
  port: 9000

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      server-addr: ${ia.nacos.host:192.168.10.128}:8848
  security:
    oauth2:
      authorizationserver:
        issuer: http://192.168.10.128:9000
        endpoint:
          oidc:
            enabled: true
      resourceserver:
        jwt:
                  jwk-set-uri: http://192.168.10.128:9000/oauth2/jwks
  data:
    redis:
      host: ${ia.redis.host:192.168.10.128}
      port: 6379

jwt:
  access-token-ttl: 3600   # 单位：秒，1小时
  refresh-token-ttl: 604800 # 单位：秒，7天
  keystore:
    path: classpath:keystore/authorization-server.p12
    password: ${KEYSTORE_PASSWORD:changeit}
    alias: jwt-rsa
    key-password: ${KEY_PASSWORD:changeit}


logging:
  level:
    org.springframework.security: DEBUG
    org.nolazy: DEBUG
    org.nolazy.authorization: DEBUG
