server:
  port: 9000

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      server-addr: ${ia.nacos.host:192.168.10.128}:8848
      discovery:
        enabled: true
  data:
    redis:
      host: ${ia.redis.host:192.168.10.128}
      port: 6379

jwt:
  access-token-ttl: 3600
  refresh-token-ttl: 604800
  keystore:
    path: classpath:keystore/authorization-server.p12
    password: ${KEYSTORE_PASSWORD:changeit}
    alias: jwt-rsa
    key-password: ${KEY_PASSWORD:changeit}

logging:
  level:
    org.springframework.security: DEBUG
    org.icedAmericanoMall: DEBUG
    org.nolazy: DEBUG
