server:
  port: 8086

spring:
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://${ia.db.host}:3306/icedamericano_mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw:root}
  cloud:
    nacos:
      server-addr: 192.168.10.128:8848
      username: nacos
      password: nacoss
      discovery:
        enabled: true

  data:
    redis:
      port: 6379
      host: 192.168.10.128
      password: redis
      client-name: search-service

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

# ElasticSearch 暂不启用（V1.1 正式上线）
search:
  elasticsearch:
    enabled: true
    host: 192.168.10.128
    port: 9200
